### ISSUE TITLE
Program to count

### ISSUE THREAD

**Issue by mana8100** [LTsoft-repo/UoR-Meliora#1]
## ToDo
- [x] Write a program that counts from 1 to 50. 
  - [x] When the number is a multiple of 3, print `Nursing`. 
  - [x] When the number is a multiple of 7, print `Meliora`. 
  - [x] If the number is a multiple of both 3 and 7, print `Nursing Meliora`. 
  - [x] If the number is not a multiple of either 3 or 7, just print the number.

**Comment by mana8100** [comment]
Closed by #3
